# Generated by Django 5.0.2 on 2024-02-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fish_Meat', models.CharField(max_length=20)),
                ('Vegetables', models.CharField(max_length=20)),
                ('Fruits', models.CharField(max_length=20)),
                ('Breakfast_Snacks', models.CharField(max_length=20)),
                ('Organic_Herbals', models.CharField(max_length=20)),
                ('Monthly_Bazar', models.CharField(max_length=20)),
            ],
        ),
    ]
