# Generated by Django 5.0.2 on 2024-02-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast_Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fish_Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Bazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organic_Herbals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_img', models.ImageField(upload_to='')),
                ('product_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='all_product',
            name='Breakfast_Snacks',
        ),
        migrations.RemoveField(
            model_name='all_product',
            name='Fish_Meat',
        ),
        migrations.RemoveField(
            model_name='all_product',
            name='Fruits',
        ),
        migrations.RemoveField(
            model_name='all_product',
            name='Monthly_Bazar',
        ),
        migrations.RemoveField(
            model_name='all_product',
            name='Organic_Herbals',
        ),
        migrations.RemoveField(
            model_name='all_product',
            name='Vegetables',
        ),
    ]
